# اختيار صورة أساس
FROM python:3.11-slim-bullseye

# تعيين مجلد العمل
WORKDIR /app

# نسخ ملف requirements وتثبيت المكتبات
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# نسخ باقي الملفات
COPY . .

# فتح البورت 7860
EXPOSE 7860

# تشغيل Uvicorn
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "7860"]
