# Étape 1 : choisir l’image de base
FROM python:3.11-slim

# Étape 2 : définir le répertoire de travail
WORKDIR /app

# Étape 3 : copier les fichiers
COPY ./ /app

# Étape 4 : installer les dépendances
RUN pip install --no-cache-dir fastapi uvicorn jinja2


# Exposer le port (7860 comme demandé)
EXPOSE 7860

# Commande de démarrage (Uvicorn)
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "7860"]